---
name: pysbf2 Bug Report

about: Create a report to help us improve

title: ''

labels: ''

assignees: semuadmin

---

**Describe the bug**

A clear and concise description of what the bug is. Please include:

1. The pysbf2 version (`>>> pysbf2.version`)
2. The **complete** Python script. Embed your code here (please do *NOT* attach *.py, *.zip, *.tgz or other executable / zipped files) ...
   ```python
   your code here
   ```
3. The error message and full traceback.
4. A binary / hexadecimal dump of the SBF data stream.

**To Reproduce**

Steps to reproduce the behaviour:
1. Any relevant device configuration (if other than factory defaults).
2. Any causal Septentrio command input(s).

**Expected Behaviour**

A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**

- The operating system you're using [e.g. Windows 11, MacOS Sequoia, Ubuntu Noble].
- The type of serial connection [e.g. USB, UART1, I2C].

**GNSS/GPS Device (please complete the following information as best you can):**

- Device Model/Generation: [e.g. MOSAIC-X5].
- Firmware Version: [e.g. 4.14.10.1].


**Additional context**

Add any other context about the problem here.
